collect:
  build: collecter
  restart: always
  links:
    - redis

redis:
  image: redis:latest
  hostname: redis
  ports:
    - "6379:6379"

web:
  build: web
  restart: always
  hostname: web
  links:
    - redis
  ports:
    - "80:5000"